services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    networks:
      - openwebui
    ports:
      - "8080:8080"
    volumes:
      - ./searxng-config/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=openwebui-search
      - SEARXNG_SECRET=your-secret-key-here
      - SEARXNG_HOSTNAME=0.0.0.0
    restart: unless-stopped

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./uploads:/app/backend/uploads:rw
      - ./storage:/app/backend/storage:rw
    ports:
      - "3000:8080"
    environment:
      # Point to local Ollama instance
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SEARXNG_QUERY_URL=http://searxng:8080/search
      # RAG and file handling settings
      - ENABLE_RAG=true
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_EMBEDDING_MODEL=all-MiniLM-L6-v2
      - RAG_CHUNK_SIZE=1000
      - RAG_CHUNK_OVERLAP=100
      - RAG_TOP_K=3
      - RAG_FILE_MAX_SIZE=50000000
      - RAG_FILE_MAX_COUNT=10
      # File upload settings
      - FILE_UPLOAD_PATH=/app/backend/uploads
      - STORAGE_PATH=/app/backend/storage
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - openwebui
    depends_on:
      - searxng

networks:
  openwebui:
    driver: bridge

volumes:
  open-webui: {}
